<?php echo $this->render('header.phtml'); ?>
<h1><?php echo $this->escape($this->title); ?></h1>
Отсортировать: 
<?php  
	$current_page = 1;
	if(isset($_GET['page'])) $current_page = $_GET['page'];
	if($_SESSION['newest']==1){
		echo "<a href='?page=".$current_page."&newest=0'> От старых к новым </a>";
} else{
		echo "<a href='?page=".$current_page."&newest=1'> От новых к старым </a>";
}
 ?>
<br><br>
<?php foreach($this->resultSet as $row) : ?>
<table>
	<tr>
		<td>
		<b>
		<?php echo $this->escape($row['name']);
		?>
		</b>
		</td>
	</tr>
	<tr>
		<td>
		<?php echo $this->escape($row['title']);
		?>
		</td>
	</tr>
	<tr>
		<td>
		<div id="ww">
		<?php echo $this->escape($row['text']);
		?>
		</div>
		</td>
	</tr>
</table>
<?php endforeach; ?>
<div class="navigator">
<?php 
echo $this->render('navigation.phtml'); 
num_page();
?>
</div>
<form action="<?php echo $this->baseUrl ?>/index" method="post">
	<div class="name">
		<label for="name">Имя</label>
		<input id="name" type="text" name="name" value="<?php if(isset($this->data)) echo $this->data['name']?>">
	</div>
	<div class="email">
		<label for="email">Email</label>
		<input id="email" type="text" name="email" value="<?php if(isset($this->data)) echo $this->data['email']?>"/>
	</div>
	<div class="title">
		<label for="title">Тема сообщения</label>
		<input id="title" type="text" name="title" value="<?php if(isset($this->data)) echo $this->data['title']?>"/>
	</div>
	<div class="text">
		<label for="text">Сообщение</label>
		<textarea id="text" type="text" name="text"><?php if(isset($this->data)) echo $this->data['text']?></textarea>
	</div>
	<div id="formbutton">
		<input type="submit" name="add"
		value="Добавить комментарий" />
	</div>
	<?php 
	if(isset($this->data)) echo $this->data['error'];
	?>
</form>
<?php echo $this->render('footer.phtml'); ?>